#' @title Treatment Effects in Interactive Fixed Effects Models
#' @description The \code{ife} package contains tools for estimating treatment
#' effects when untreated potential outcomes are generated by an interactive
#' fixed effects model.
#'
#' @docType package
#' @name ife
#' @import stats
#' @import utils
#' @import pte
NULL
