#' @title Treatment Effects in Interactive Fixed Effects Models
#'
#' @description The \code{ife} package contains tools for estimating treatment
#' effects when untreated potential outcomes are generated by an interactive
#' fixed effects model.
#'
#' @keywords internal
"_PACKAGE"
